version: '3.9'

services:
  chat-eureka:
    hostname: eurekahost
    build:
      context: ./chat-eureka
      dockerfile: docker/Dockerfile
    ports: 
      - 8761:8761
    networks:
      - chat-net

  chat-gw:
    hostname: gwhost
    build:
      context: ./chat-gw
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - chat-eureka

  chat-server-1:
    hostname: serverhost-1
    build: 
      context: ./chat-server
      dockerfile: docker/Dockerfile
    ports:
      - 8081:8080
    environment:
      - REDIS_HOST=redishost
    depends_on:
      - chat-eureka
      - redis
    networks: 
      - chat-net

  chat-server-2:
    hostname: serverhost-2
    build:
      context: ./chat-server
      dockerfile: docker/Dockerfile
    ports:
      - 8082:8080
    environment:
      - REDIS_HOST=redishost
    depends_on: 
      - chat-eureka
      - redis
    networks: 
      - chat-net

  chat-user:
    hostname: userhost
    build:
      context: ./chat-user
      dockerfile: docker/app/Dockerfile
    ports:
      - 8083:8080
    environment:
      - USER_DB_HOST=jdbc:mysql://userdbhost:3306/user_db
    depends_on:
      - chat-eureka
      - user-db
    networks: 
      - chat-net

  chat-client:
    hostname: clienthost
    build: 
      context: ./chat-client
      dockerfile: docker/Dockerfile
    ports:
      - 3000:3000
    networks: 
      - chat-net

  redis:
    hostname: redishost
    image: redis
    expose:
      - 6379:6379
    networks: 
      - chat-net

  user-db:
    hostname: userdbhost
    build:
      context: ./chat-user
      dockerfile: docker/db/Dockerfile
    expose:
      - 3306:3306
    networks:
      - chat-net

networks:
  chat-net: