version: '3.9'

services:
  chat-server:
    hostname: serverhost
    build: ./websocket-server
    ports:
      - 8080:8080
  chat-client:
    hostname: clienthost
    build: ./websocket-client
    ports:
      - 3000:3000
