spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  jackson:
    serialization:
      indent_output: true

role:
  user: ROLE_USER
  admin: ROLE_ADMIN

app:
  secret: secret
  duration:
    # in minutes
    access-token: 30
    # in days
    refresh-token: 30

server:
  error:
    include-message: always

logging:
  level:
    root: info