spring:
  application:
    name: chat-gw-service

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://127.0.0.1:3000
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
      routes:
        - id: chat-user-service
          uri: lb://CHAT-USER-SERVICE
          predicates:
            - Path=/chat/user/**
        - id: chat-server-service
          uri: lb://CHAT-SERVER-SERVICE
          predicates:
            - Path=/chat/room/**, /chat/rooms/**, /chat/login
          filters:
            - GWAuthFilter
#            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

auth:
  secret: secret
  issuer: chat-user-service/chat/user/signin
  role:
    user: ROLE_USER
    admin: ROLE_ADMIN

logging:
  level:
    root: trace