spring:
  cloud:
    gateway:
      routes:
        - id: chat-server-0
          uri: http://localhost:8080
          predicates:
            - Path=/chat/0/**
          filters:
            - RewritePath=/chat/0/(?<segment>.*), /chat/${segment}
        - id: chat-server-1
          uri: http://localhost:8081
          predicates:
            - Path=/chat/1/**
          filters:
            - RewritePath=/chat/1/(?<segment>.*), /chat/${segment}