spring:
  application:
    name: chat-gw-service

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: '*'
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
      routes:
        - id: chat-user-service
          uri: lb://CHAT-USER-SERVICE
          predicates:
            - Path=/chat/user/**
        - id: chat-server-service
          uri: lb://CHAT-SERVER-SERVICE
          predicates:
            - Path=/chat/room/**, /chat/rooms/**, /chat/login
#          filters:
#            - AuthFilter
app:
  secret: secret

logging:
  level:
    root: trace